### ISSUE TITLE
Add a new page named How it Works.

### ISSUE THREAD

**Issue by jugeshraghav** [siv2r/kidney-exchange#305]
### Can you please describe the problem to be solved?
For new users it will be easy for them if they find such a page which helps them to understand how to donate or  request for the organ.

### Can you give some suggestions?

If there are multiple solutions, please present each one separately.

Save comparisons for the very end.

**Comment by jugeshraghav** [comment]
Please assign this issue to me.

**Comment by jugeshraghav** [comment]
This page will give details of how a person can donate or request for the organ in detail.

**Comment by siv2r** [comment]
Same suggestions as this: https://github.com/siv2r/kidney-exchange/issues/304#issuecomment-862017225l
Additionally, you could include detailed explanations of this website's different features, which is required. 
I feel explanations about organ requests don't suit this context since this website is for doctors and not for the patients.

**Comment by siv2r** [comment]
Feel free to ask for doubts/help in the discord server :)

**Comment by harshita9621** [comment]
Can I work on this issue?

**Comment by siv2r** [comment]
@harshita9621 Sure! Go ahead. Feel free to ask for doubts/help in the discord server.

**Comment by jugeshraghav** [comment]
Actually i had semester exams so i could not work on the issue. Can i continue to work on it. @siv2r

**Comment by siv2r** [comment]
@jugeshraghav Sure! It would be great if both of you could collaborate.

**Comment by riasenpai** [comment]
@jugeshraghav @harshita9621 any updates?
